### ISSUE TITLE
RWD

### ISSUE THREAD

**Issue by PTDTW** [HansHans135/BoardMate#1]
### 我覺得你的那個RWD真的需要優化!
> 截圖

![Screenshot_20230609-014919.png](https://github.com/HansHans135/boardmate/assets/113230263/9e5c58a1-d5a7-4a67-b370-90ba7763c6e0)

![Screenshot_20230609-014930.png](https://github.com/HansHans135/boardmate/assets/113230263/11cfce24-6f9e-4844-841b-97386f5bedeb)

---

這是其中兩個
全部都頁面都會

**Comment by HansHans135** [comment]
![Screenshot_2023-06-09-09-05-56-328_com android chrome](https://github.com/HansHans135/boardmate/assets/94590267/0c13fd7c-2571-4dc0-93d4-dee5e689ecb8)
看起來是你的問題

**Comment by sus2790** [comment]
~~顧客至上~~ 每個人的設備不太一樣 老實說挺正常的
