### ISSUE TITLE
v2 建議

### ISSUE THREAD

**Issue by sus2790** [HansHans135/boardmate#2]
# 基本
- 跑一遍black、isort不然真的挺醜的。

# 未來發展
- 完全使用非同步package，
ex: `aiohttp` `asyncio` `aiofiles`
- 去除非必要的 `try` `except`  [Sourcery](https://docs.sourcery.ai/Reference/Python/Default-Rules/do-not-use-bare-except/)
- 不使用random，而是使用 [Secrets](https://docs.python.org/zh-tw/3/library/secrets.html#module-secrets)
- 完全移除JSON 快捷但不推薦 [Is it okay to use JSON as a database?](https://www.quora.com/Is-it-okay-to-use-JSON-as-a-database)
- 文檔 (docstrings, readthedocs) [PEP257](https://peps.python.org/pep-0257/)
- return types, ... [typing](https://docs.python.org/3/library/typing.html)
- CI

**Comment by HansHans135** [comment]
1. asyncio正在實作
2. 例如哪裡
3. K
4. 可能不會
5. 會找時間
6. 會考慮
7. 可能不會

**Comment by sus2790** [comment]
@HansHans135 
![image](https://github.com/HansHans135/boardmate/assets/104747821/7b7271e7-a01b-4429-8480-dfa1cfe0a1b7)

**Comment by HansHans135** [comment]
目前正在著手計畫中，請參考 [v2-dev](https://github.com/HansHans135/boardmate/tree/v2-dev)

**Comment by sus2790** [comment]
你不說我都忘了

**Comment by HansHans135** [comment]
[v2.0.0-beta](https://github.com/HansHans135/boardmate/releases/tag/v2.0.0) 已發布

**Comment by sus2790** [comment]
亨哥牛逼
