### ISSUE TITLE
出現運行錯誤

### ISSUE THREAD

**Issue by phdassice** [HansHans135/BoardMate#3]
![Screenshot_20240122_075146_Chrome](https://github.com/HansHans135/boardmate/assets/96707438/8f1254ec-aa32-4858-9ad2-6e70ee127a90)

**Comment by phdassice** [comment]
![image](https://github.com/HansHans135/boardmate/assets/96707438/5ca08bbf-d49c-438a-805f-a79d2e5e0417)

**Comment by HansHans135** [comment]
很明顯的，你的配置有誤

**Comment by phdassice** [comment]
> 很明顯的，你的配置有誤
還是我把我的json配置給你看
